---

- name: Install unattended-upgrades
  apt:
    name:
      - unattended-upgrades
      - apt-listchanges

- name: Enable unattended upgrades
  copy:
    src: 20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades